[style.description]
underline = false
bold = false
italic = false

[style.command_name]
#Orange
foreground = { rgb = { r = 223, g = 174, b = 104 } }
underline = false
bold = true
italic = false

[style.example_text]
# Blue
foreground = { rgb = { r = 113, g = 153, b = 238 } }
underline = false
bold = false
italic = true

[style.example_code]
# Purple
foreground = { rgb = { r = 164, g = 133, b = 221 } }
underline = false
bold = false
italic = false

[style.example_variable]
# Green
foreground = { rgb = { r = 149, g = 197, b = 98 } }
underline = true
bold = true
italic = false

[display]
compact = false
use_pager = true
show_title = true

[updates]
auto_update = true
auto_update_interval_hours = 720
archive_source = "https://github.com/tldr-pages/tldr/releases/latest/download/"
tls_backend = "rustls-with-webpki-roots"

[directories]
cache_dir = "/Users/ccaio/.cache/tealdeer"
custom_pages_dir = "/Users/ccaio/.local/share/tealdeer"

[search]
languages = ['en', 'pt_br']
