#!/usr/bin/env bash

SESSION=""
EXCLUDE=""
SEP='§'

while getopts "s:x:" opt; do
  case "$opt" in
    s) SESSION="$OPTARG" ;;
    x) EXCLUDE="$OPTARG" ;;
    *) exit 1 ;;
  esac
done

if [ -n "$SESSION" ]; then
  list_flag="-t $SESSION"
  fmt="#{window_activity}${SEP}#{session_name}:#{window_index}${SEP}#{window_name} (#{window_index}) [#{pane_current_command}]"
else
  list_flag="-a"
  fmt="#{window_activity}${SEP}#{session_name}:#{window_index}${SEP}#{window_name} | #{session_name} (#{window_index}) [#{pane_current_command}]"
fi

if [ -n "$EXCLUDE" ]; then
  session_exclude="grep -v '${SEP}${EXCLUDE}:'"
else
  session_exclude="cat"
fi

list_cmd="tmux list-windows $list_flag -F '$fmt' | $session_exclude | sort -rn | cut -d'$SEP' -f2-"

target=$(
  eval "$list_cmd" |
    fzf --reverse --ansi \
      --delimiter="$SEP" \
      --with-nth '2..' \
      --border=rounded --border-label-pos=2 --border-label=' 󰖯 Window Picker ' \
      --prompt '  ' \
      --header 'C-k:  | C-u/d: ' \
      --preview "tmux capture-pane -t {1} -ep -S - 2>/dev/null | tail -n $(tput lines) || echo 'No preview available'" \
      --preview-window 'right:60%' --height='100%' \
      --exit-0 \
      --bind 'ctrl-d:preview-half-page-down,ctrl-u:preview-half-page-up' \
      --bind "ctrl-k:execute-silent(tmux kill-window -t {1})+reload($list_cmd)" |
    cut -d"$SEP" -f1
)

[ -n "$target" ] && tmux switch-client -t "$target"
