return {
  "folke/which-key.nvim",
  opts = {
    spec = {
      -- mini.bracketed (no auto-match)
      { "[i", icon = { icon = " ", color = "cyan" }, desc = "Prev Indent Change" },
      { "]i", icon = { icon = " ", color = "cyan" }, desc = "Next Indent Change" },
      { "[I", icon = { icon = " ", color = "cyan" }, desc = "First Indent Change" },
      { "]I", icon = { icon = " ", color = "cyan" }, desc = "Last Indent Change" },
      { "[j", icon = { icon = "󱋿 ", color = "green" }, desc = "Prev Jump" },
      { "]j", icon = { icon = "󱋿 ", color = "green" }, desc = "Next Jump" },
      { "[J", icon = { icon = "󱋿 ", color = "green" }, desc = "First Jump" },
      { "]J", icon = { icon = "󱋿 ", color = "green" }, desc = "Last Jump" },
      { "[l", icon = { icon = "󰿄 ", color = "green" }, desc = "Prev Location" },
      { "]l", icon = { icon = "󰿅 ", color = "green" }, desc = "Next Location" },
      { "[L", icon = { icon = "󰿄 ", color = "green" }, desc = "First Location" },
      { "]L", icon = { icon = "󰿅 ", color = "green" }, desc = "Last Location" },
      { "[o", icon = { icon = " ", color = "azure" }, desc = "Prev Oldfile" },
      { "]o", icon = { icon = " ", color = "azure" }, desc = "Next Oldfile" },
      { "[O", icon = { icon = " ", color = "azure" }, desc = "First Oldfile" },
      { "]O", icon = { icon = " ", color = "azure" }, desc = "Last Oldfile" },
      { "[t", icon = { icon = " ", color = "purple" }, desc = "Prev Treesitter Node" },
      { "]t", icon = { icon = " ", color = "purple" }, desc = "Next Treesitter Node" },
      { "[T", icon = { icon = " ", color = "purple" }, desc = "First Treesitter Node" },
      { "]T", icon = { icon = " ", color = "purple" }, desc = "Last Treesitter Node" },
      { "[u", icon = { icon = "󰕌 ", color = "yellow" }, desc = "Prev Undo" },
      { "]u", icon = { icon = "󰕌 ", color = "yellow" }, desc = "Next Undo" },
      { "[U", icon = { icon = "󰕌 ", color = "yellow" }, desc = "First Undo" },
      { "]U", icon = { icon = "󰕌 ", color = "yellow" }, desc = "Last Undo" },
      { "[x", icon = { icon = " ", color = "red" }, desc = "Prev Conflict Marker" },
      { "]x", icon = { icon = " ", color = "red" }, desc = "Next Conflict Marker" },
      { "[X", icon = { icon = " ", color = "red" }, desc = "First Conflict Marker" },
      { "]X", icon = { icon = " ", color = "red" }, desc = "Last Conflict Marker" },

      -- LazyVim core (no auto-match)
      { "[e", icon = { icon = " ", color = "red" }, desc = "Prev Error" },
      { "]e", icon = { icon = " ", color = "red" }, desc = "Next Error" },

      -- Git hunks (no auto-match)
      { "[h", icon = { icon = " ", color = "orange" }, desc = "Prev Hunk" },
      { "]h", icon = { icon = " ", color = "orange" }, desc = "Next Hunk" },
      { "[H", icon = { icon = " ", color = "orange" }, desc = "First Hunk" },
      { "]H", icon = { icon = " ", color = "orange" }, desc = "Last Hunk" },

      -- Treesitter textobjects (no auto-match)
      { "[f", icon = { icon = "󰊕 ", color = "purple" }, desc = "Prev Function Start" },
      { "]f", icon = { icon = "󰊕 ", color = "purple" }, desc = "Next Function Start" },
      { "[F", icon = { icon = "󰊕 ", color = "purple" }, desc = "Prev Function End" },
      { "]F", icon = { icon = "󰊕 ", color = "purple" }, desc = "Next Function End" },
      { "[c", icon = { icon = " ", color = "purple" }, desc = "Prev Class Start" },
      { "]c", icon = { icon = " ", color = "purple" }, desc = "Next Class Start" },
      { "[C", icon = { icon = " ", color = "purple" }, desc = "Prev Class End" },
      { "]C", icon = { icon = " ", color = "purple" }, desc = "Next Class End" },
      { "[a", icon = { icon = " ", color = "purple" }, desc = "Prev Parameter" },
      { "]a", icon = { icon = " ", color = "purple" }, desc = "Next Parameter" },
      { "[A", icon = { icon = " ", color = "purple" }, desc = "Prev Parameter End" },
      { "]A", icon = { icon = " ", color = "purple" }, desc = "Next Parameter End" },
      { "[m", icon = { icon = " ", color = "purple" }, desc = "Prev Method" },
      { "]m", icon = { icon = " ", color = "purple" }, desc = "Next Method" },
      { "[M", icon = { icon = " ", color = "purple" }, desc = "Prev Method End" },
      { "]M", icon = { icon = " ", color = "purple" }, desc = "Next Method End" },

      -- z-prefixed remaps
      { "[z", group = "extra nav", icon = { icon = "󰐕 ", color = "grey" } },
      { "]z", group = "extra nav", icon = { icon = "󰐕 ", color = "grey" } },
      { "[zc", icon = { icon = " ", color = "green" }, desc = "Prev Comment Block" },
      { "]zc", icon = { icon = " ", color = "green" }, desc = "Next Comment Block" },
      { "[zq", icon = { icon = "󰙵 ", color = "red" }, desc = "Prev Quickfix" },
      { "]zq", icon = { icon = "󰙵 ", color = "red" }, desc = "Next Quickfix" },
      { "[zt", icon = { icon = " ", color = "blue" }, desc = "Prev Todo Comment" },
      { "]zt", icon = { icon = " ", color = "blue" }, desc = "Next Todo Comment" },
      { "[zw", icon = { icon = "󰀦 ", color = "yellow" }, desc = "Prev Warning" },
      { "]zw", icon = { icon = "󰀦 ", color = "yellow" }, desc = "Next Warning" },
      { "[zy", icon = { icon = "󰆏 ", color = "orange" }, desc = "Prev Yank (mini)" },
      { "]zy", icon = { icon = "󰆏 ", color = "orange" }, desc = "Next Yank (mini)" },

      -- Others
      { "[s", icon = { icon = " ", color = "orange" }, desc = "Previous mispelled word" },
      { "]s", icon = { icon = " ", color = "orange" }, desc = "Next mispelled word" },
      { "[q", icon = { icon = "󰙵 ", color = "red" }, desc = "Prev Trouble/Quickfix Item" },
      { "]q", icon = { icon = "󰙵 ", color = "red" }, desc = "Next Trouble/Quickfix Item" },
      { "[Q", icon = { icon = "󰙵 ", color = "red" }, desc = "First Quickfix Item" },
      { "]Q", icon = { icon = "󰙵 ", color = "red" }, desc = "Last Quickfix Item" },

      -- mini.operators
      { "g=", icon = { icon = " ", color = "green" }, desc = "Evaluate", mode = { "n", "x" } },
      { "g==", icon = { icon = " ", color = "green" }, desc = "Evaluate line" },
      { "gx", icon = { icon = " ", color = "cyan" }, desc = "Exchange", mode = { "n", "x" } },
      { "gxx", icon = { icon = " ", color = "cyan" }, desc = "Exchange line" },
      { "gm", icon = { icon = "󰎃 ", color = "blue" }, desc = "Multiply", mode = { "n", "x" } },
      { "gmm", icon = { icon = "󰎃 ", color = "blue" }, desc = "Multiply line" },
      { "gr", icon = { icon = " ", color = "orange" }, desc = "Replace", mode = { "n", "x" } },
      { "grr", icon = { icon = " ", color = "orange" }, desc = "Replace line" },
      { "gz", icon = { icon = "󰒺 ", color = "purple" }, desc = "Sort", mode = { "n", "x" } },
      { "gzz", icon = { icon = "󰒺 ", color = "purple" }, desc = "Sort line" },
    },
  },
}
