return {
  "folke/which-key.nvim",
  opts = {
    icons = {
      rules = {
        { pattern = "jump", icon = "󱋿 ", color = "green" },
        { pattern = "indent", icon = " ", color = "cyan" },
        { pattern = "[nl].*location$", icon = "󰿅 ", color = "green" },
        { pattern = "[fp].*location$", icon = "󰿄 ", color = "green" },
        { pattern = "oldfile$", icon = " ", color = "azure" },
        { pattern = "treesitter", icon = " ", color = "purple" },
        { pattern = "undo", icon = "󰕌 ", color = "yellow" },
        { pattern = "conflict", icon = " ", color = "red" },
        { pattern = "error", icon = " ", color = "red" },
        { pattern = "hunk", icon = " ", color = "orange" },
        { pattern = "function", icon = "󰊕 ", color = "purple" },
        { pattern = "class", icon = " ", color = "purple" },
        { pattern = "parameter", icon = " ", color = "purple" },
        { pattern = "method", icon = " ", color = "purple" },
        { pattern = "todo", icon = " ", color = "blue" },
        { pattern = "comment", icon = "󰙵 ", color = "green" },
        { pattern = "quickfix", icon = " ", color = "green" },
        { pattern = "warning", icon = "󰀦 ", color = "yellow" },
        { pattern = "yank", icon = "󰆏 ", color = "orange" },
        { pattern = "mispelled", icon = " ", color = "red" },
        { pattern = "sniprun", icon = " ", color = "purple" },
        { pattern = "surround", icon = " ", color = "purple" },
      },
    },
    spec = {
      -- mini.bracketed (no auto-match)
      { "[i", desc = "Prev Indent Change" },
      { "]i", desc = "Next Indent Change" },
      { "[I", desc = "First Indent Change" },
      { "]I", desc = "Last Indent Change" },
      { "[j", desc = "Prev Jump" },
      { "]j", desc = "Next Jump" },
      { "[J", desc = "First Jump" },
      { "]J", desc = "Last Jump" },
      { "[l", desc = "Prev Location" },
      { "]l", desc = "Next Location" },
      { "[L", desc = "First Location" },
      { "]L", desc = "Last Location" },
      { "[o", desc = "Prev Oldfile" },
      { "]o", desc = "Next Oldfile" },
      { "[O", desc = "First Oldfile" },
      { "]O", desc = "Last Oldfile" },
      { "[t", desc = "Prev Treesitter Node" },
      { "]t", desc = "Next Treesitter Node" },
      { "[T", desc = "First Treesitter Node" },
      { "]T", desc = "Last Treesitter Node" },
      { "[u", desc = "Prev Undo" },
      { "]u", desc = "Next Undo" },
      { "[U", desc = "First Undo" },
      { "]U", desc = "Last Undo" },
      { "[x", desc = "Prev Conflict Marker" },
      { "]x", desc = "Next Conflict Marker" },
      { "[X", desc = "First Conflict Marker" },
      { "]X", desc = "Last Conflict Marker" },

      -- TODO: Complete all groups

      -- LazyVim core (no auto-match)
      { "[e", desc = "Prev Error" },
      { "]e", desc = "Next Error" },

      -- Git hunks (no auto-match)
      { "[h", desc = "Prev Hunk" },
      { "]h", desc = "Next Hunk" },
      { "[H", desc = "First Hunk" },
      { "]H", desc = "Last Hunk" },

      -- Treesitter textobjects (no auto-match)
      { "[f", desc = "Prev Function Start" },
      { "]f", desc = "Next Function Start" },
      { "[F", desc = "Prev Function End" },
      { "]F", desc = "Next Function End" },
      { "[c", desc = "Prev Class Start" },
      { "]c", desc = "Next Class Start" },
      { "[C", desc = "Prev Class End" },
      { "]C", desc = "Next Class End" },
      { "[a", desc = "Prev Parameter" },
      { "]a", desc = "Next Parameter" },
      { "[A", desc = "Prev Parameter End" },
      { "]A", desc = "Next Parameter End" },
      { "[m", desc = "Prev Method" },
      { "]m", desc = "Next Method" },
      { "[M", desc = "Prev Method End" },
      { "]M", desc = "Next Method End" },

      -- z-prefixed remaps
      { "[z", group = "extra nav", icon = { icon = "󰐕 ", color = "grey" } },
      { "]z", group = "extra nav", icon = { icon = "󰐕 ", color = "grey" } },
      { "[zc", desc = "Prev Comment Block" },
      { "]zc", desc = "Next Comment Block" },
      { "[zq", desc = "Prev Quickfix" },
      { "]zq", desc = "Next Quickfix" },
      { "[zt", desc = "Prev Todo Comment" },
      { "]zt", desc = "Next Todo Comment" },
      { "[zw", desc = "Prev Warning" },
      { "]zw", desc = "Next Warning" },
      { "[zy", desc = "Prev Yank (mini)" },
      { "]zy", desc = "Next Yank (mini)" },

      -- Others
      { "[s", desc = "Previous mispelled word" },
      { "]s", desc = "Next mispelled word" },
      { "[q", desc = "Prev Trouble/Quickfix Item" },
      { "]q", desc = "Next Trouble/Quickfix Item" },
      { "[Q", desc = "First Quickfix Item" },
      { "]Q", desc = "Last Quickfix Item" },
      { "<leader>K", icon = { icon = "󰘥", color = "purple" }, desc = "Man/Help for Keyword" },

      -- mini.operators
      { "g=", icon = { icon = " ", color = "green" }, desc = "Evaluate", mode = { "n", "x" } },
      { "g==", icon = { icon = " ", color = "green" }, desc = "Evaluate line" },
      { "gx", icon = { icon = " ", color = "cyan" }, desc = "Exchange", mode = { "n", "x" } },
      { "gxx", icon = { icon = " ", color = "cyan" }, desc = "Exchange line" },
      { "gm", icon = { icon = "󰎃 ", color = "blue" }, desc = "Multiply", mode = { "n", "x" } },
      { "gmm", icon = { icon = "󰎃 ", color = "blue" }, desc = "Multiply line" },
      { "gR", icon = { icon = " ", color = "orange" }, desc = "Replace", mode = { "n", "x" } },
      { "grr", icon = { icon = " ", color = "orange" }, desc = "Replace line" },
      { "gz", icon = { icon = "󰒺 ", color = "purple" }, desc = "Sort", mode = { "n", "x" } },
      { "gzz", icon = { icon = "󰒺 ", color = "purple" }, desc = "Sort line" },
    },
  },
}
