# XDG Config paths
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# ZSH config dir
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

export EDITOR='nvim'

# EZA Default config dir
export EZA_CONFIG_DIR="$XDG_CONFIG_HOME/eza"

# AWS
export SHOW_AWS_PROMPT=false # Fix AWS extension trash prompt
export AWS_PROFILE='default'
export AWS_CONFIG_DIR="${XDG_CONFIG_HOME}/aws"

# Python plugin auto venv activate/deactivate vars
export PYTHON_VENV_NAME=".venv"
export PYTHON_VENV_NAMES=($PYTHON_VENV_NAME .env venv env)
export PYTHON_AUTO_VRUN=true

# Tealdeer config path
export TEALDEER_CONFIG_DIR="${XDG_CONFIG_HOME}/tealdeer"

# Cargo Env config
source "$HOME/.cargo/env"

# Set brew paths
export HOMEBREW_PREFIX="/opt/homebrew";
export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
export HOMEBREW_REPOSITORY="/opt/homebrew";
fpath[1,0]="/opt/homebrew/share/zsh/site-functions";
export FPATH;
eval "$(/usr/bin/env PATH_HELPER_ROOT="/opt/homebrew" /usr/libexec/path_helper -s)"
[ -z "${MANPATH-}" ] || export MANPATH=":${MANPATH#:}";
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";
export HOMEBREW_NO_ENV_HINTS=1
