# SECTION: Sources

[[ -f ${ZDOTDIR}/vars_opts.zsh ]] && source $ZDOTDIR/vars_opts.zsh
[[ -f ${ZDOTDIR}/aliases.zsh ]] && source ${ZDOTDIR}/aliases.zsh
[[ -f ${ZDOTDIR}/zsh_functions.zsh ]] && source ${ZDOTDIR}/zsh_functions.zsh

# Work specific settings
[[ -f ${AWS_CONFIG_DIR}/zsh_aws.zsh ]] && source ${AWS_CONFIG_DIR}/zsh_aws.zsh

# SECTION: Stuff that need to be loaded early

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# SECTION: zinit and zstyle

# p10k
zinit ice depth=1; zinit light romkatv/powerlevel10k

# ZVM
zinit ice depth=1; zinit light jeffreytse/zsh-vi-mode

# Syntax highlighting
zinit ice wait lucid as"program" from"gh-r" pick"zsh-patina-*/zsh-patina" atload'eval "$(zsh-patina activate)"'
zinit light michel-kraemer/zsh-patina

# Other plugins
zinit ice wait lucid; zinit light zsh-users/zsh-completions
zinit ice wait lucid; zinit light zsh-users/zsh-autosuggestions
zinit ice wait lucid atinit'AUTOCD=1'; zinit light z-shell/zsh-eza

# Add in snippets
zinit ice wait lucid; zinit snippet OMZL::functions.zsh
zinit ice wait lucid; zinit snippet OMZP::sudo
zinit ice wait lucid; zinit snippet OMZP::aws
zinit ice wait lucid; zinit snippet OMZP::command-not-found
zinit ice wait lucid; zinit snippet OMZP::macos
zinit ice wait lucid; zinit snippet OMZP::python
zinit ice wait lucid; zinit snippet OMZP::colored-man-pages
zinit ice wait lucid; zinit snippet OMZP::uv
zinit ice wait lucid; zinit snippet OMZL::clipboard.zsh
zinit ice wait lucid; zinit snippet OMZL::termsupport.zsh

 zinit ice atclone"dircolors -b LS_COLORS > clrs.zsh" \
     atpull'%atclone' pick"clrs.zsh" nocompile'!' \
     atload'zstyle ":completion:*" list-colors “${(s.:.)LS_COLORS}”'
zinit ice wait lucid; zinit light trapd00r/LS_COLORS

# SECTION: Autocomplete 

# Load tab completion
zinit light Aloxaf/fzf-tab

# Load completions after all plugins/snippets have registered compdef calls
autoload -Uz compinit
if [[ -n ${ZCOMPDUMP_FILE}(#qN.mh+24) ]]; then
  compinit -d ${ZCOMPDUMP_FILE}
else
  compinit -C -d ${ZCOMPDUMP_FILE}
fi
[[ ${ZCOMPDUMP_FILE} -nt ${ZCOMPDUMP_FILE}.zsc ]] && zcompile ${ZCOMPDUMP_FILE}
zicdreplay

# Completion styling
zstyle ':completion:*' menu no # Tab opens cmp menu
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS} ma=0\;33 # colorize cmp menu
zstyle ':completion:*' cache-path "$XDG_CACHE_HOME/zsh/zcompcache" # completion cache
zstyle ':completion:*' squeeze-slashes false # allow /*/ completion
zstyle ':completion:*:git-checkout:*' sort false 

# fzf-tab
zstyle ':fzf-tab:*' fzf-flags --height=60% --cycle --preview-window=right:60% --layout=reverse
zstyle ':fzf-tab:complete:(cp|cd|nvim|z|vim|eza|bat)*' fzf-preview \
  'if [ -d $realpath ]; then 
    eza --icons=always --tree --color=always --level=2 $realpath; 
  else 
    bat -n --color=always --line-range :500 $realpath; 
  fi'
zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup
zstyle ':fzf-tab:*' popup-min-size 150 25

# SECTION: Vim Mode Keybinds

  # Append last word of previous prompt
  zvm_bindkey vicmd '\e.' append-last-word
  zvm_bindkey viins '\e.' insert-last-word

  # Kill word up to symbol with opt-backspace
  zvm_bindkey viins '^[^?' backward-kill-to-symbol
  zvm_bindkey vicmd '^[^?' backward-kill-to-symbol
  # Kill word up to next space with opt-shift-backspace
  zvm_bindkey viins '^[^H' backward-kill-word
  zvm_bindkey vicmd '^[^H' backward-kill-word

  # Bind ctrl+p/n and j/k (cmd) for history search in both modes
  zvm_bindkey viins '^p' history-search-backward
  zvm_bindkey viins '^n' history-search-forward
  zvm_bindkey vicmd 'k' history-search-backward
  zvm_bindkey vicmd 'j' history-search-forward
  zvm_bindkey vicmd '^p' history-search-backward
  zvm_bindkey vicmd '^n' history-search-forward

# SECTION: End of file evals

# Use cached function instead of plain eval to save startup time
_cache_eval fzf --zsh
_cache_eval zoxide init --cmd cd zsh
_cache_eval atuin init zsh --disable-up-arrow
unfunction _cache_eval

if [[ ! -f $XDG_CONFIG_HOME/p10k/tokyo-evenings.zsh ]]; then 
  source $XDG_CONFIG_HOME/p10k/p10k.zsh
else
  source $XDG_CONFIG_HOME/p10k/tokyo-evenings.zsh
fi

#eval "$(oh-my-posh init zsh --config $HOME/.config/omp/tokyo_evenings.yaml)"
#eval "$(starship init zsh)"
